services:
  api:
    build:
      context: .
      dockerfile: /docker/api/Dockerfile
    image: ollaix_api
    container_name: ollaix_api
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_ADDRESS=http://ollaix_ollama:11434
    depends_on:
      - ollaix_ollama
    networks:
      - ollaix_network

  ollaix_ollama:
    build:
      context: .
      dockerfile: /docker/ollama/Dockerfile
    image: ollaix_ollama
    container_name: ollaix_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollaix_ollama_volume:/root/.ollama
    networks:
      - ollaix_network

volumes:
  ollaix_ollama_volume:
    name: ollaix_ollama_volume

networks:
  ollaix_network:
    name: ollaix_network
